<?php

declare(strict_types=1);

namespace Database\Seeders\AggressiveTemplates;

/**
 * Nine alert-family templates. Each has a distinct hero, accent palette,
 * and structural shape so recipients can visually identify the email type
 * in under 2 seconds.
 */
final class AlertTemplates
{
    public function all(): array
    {
        return [
            $this->alertCritical(),
            $this->alertHigh(),
            $this->tier1Advisory(),
            $this->annex2Hit(),
            $this->alertCaseFile(),
            $this->breach717(),
            $this->escalation(),
            $this->pheicAdvisory(),
            $this->alertClosed(),
        ];
    }

    // ── Shared CSS snippets (inline) ────────────────────────────────────
    private const WRAP_OPEN = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#EEF2F7;font-family:Arial,Helvetica,sans-serif;color:#0F172A;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#EEF2F7;padding:24px 12px;"><tr><td align="center"><table role="presentation" width="640" cellpadding="0" cellspacing="0" style="max-width:640px;background:#FFFFFF;border-radius:10px;overflow:hidden;box-shadow:0 4px 16px rgba(15,23,42,0.08);">';
    private const WRAP_CLOSE = '</table></td></tr></table></body></html>';

    private function footer(string $tone): string
    {
        return <<<HTML
<tr><td style="padding:18px 28px 12px;background:#F1F5F9;border-top:1px solid #E2E8F0;">
  <p style="margin:0;font-size:11px;color:#475569;line-height:1.5;">
    <strong>{{country_name}} POE Sentinel</strong> · {$tone} · WHO IHR 2005 &amp; AFRO IDSR 3rd Ed. aligned.<br>
    Alert <strong>{{alert_code}}</strong> · {{risk_level_label}} · fired {{alert_created_ago}} at {{alert_created_at}}.<br>
    Open in console → <a href="{{console_url}}" style="color:#1D4ED8;text-decoration:none;font-weight:600;">{{console_url}}</a>
  </p>
</td></tr>
<tr><td style="padding:8px 28px 18px;background:#F1F5F9;">
  <p style="margin:0;font-size:10px;color:#64748B;line-height:1.4;">
    This is a transactional public-health alert generated by the national surveillance pipeline. Do not reply; coordinate through the escalation ladder.<br>
    Generated {{now}} UTC · template {{alert_code}} · recipient action expected within {{ack_sla_hours}}h.
  </p>
</td></tr>
HTML;
    }

    // ═════════════════════════════════════════════════════════════════════
    //  ALERT_CRITICAL
    // ═════════════════════════════════════════════════════════════════════
    private function alertCritical(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#7F1D1D 0%,#B91C1C 60%,#DC2626 100%);padding:24px 28px;">
  <div style="font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#FECACA;font-weight:700;">{{country_name}} · POE SENTINEL · IHR 2005</div>
  <div style="margin-top:6px;font-size:12px;color:#FECACA;font-weight:600;">CRITICAL PUBLIC HEALTH ALERT · acknowledge within {{ack_hours}} hours</div>
  <div style="margin-top:10px;font-size:26px;font-weight:800;color:#FFFFFF;line-height:1.15;">⛔ {{alert_title}}</div>
  <div style="margin-top:6px;font-size:14px;color:#FECACA;">{{summary}}</div>
  <div style="margin-top:14px;background:rgba(0,0,0,0.28);border:1px solid rgba(255,255,255,0.2);border-radius:6px;padding:10px 14px;">
    <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#FFFFFF;opacity:0.9;">Acknowledge by</div>
    <div style="font-size:15px;color:#FFFFFF;font-weight:700;margin-top:2px;">{{ack_deadline}} ({{ack_hours}}h SLA)</div>
    <div style="font-size:12px;color:#FECACA;margin-top:4px;">Escalation path: {{escalation_ladder}}</div>
  </div>
</td></tr>

<tr><td style="padding:22px 28px 6px;">
  <p style="margin:0;font-size:13px;color:#0F172A;">This alert was raised because a patient at the named Point of Entry meets CRITICAL surveillance criteria under IHR 2005 and national IDSR guidance. Full case dossier, disease intelligence, and the exact actions expected of you follow below.</p>
</td></tr>

<tr><td style="padding:18px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">WHAT · WHERE · WHO</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #FEE2E2;border-radius:8px;background:#FEF2F2;">
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:12px;color:#7F1D1D;">Alert code</td><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:13px;text-align:right;font-weight:700;color:#7F1D1D;">{{alert_code}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:12px;color:#7F1D1D;">Risk classification</td><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:13px;text-align:right;font-weight:700;color:#B91C1C;">{{risk_level_label}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:12px;color:#7F1D1D;">Point of Entry · District</td><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:13px;text-align:right;font-weight:700;">{{poe_code}} · {{district_code}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:12px;color:#7F1D1D;">Country · Province</td><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:13px;text-align:right;">{{country_name}} · {{province_code}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:12px;color:#7F1D1D;">Detected by</td><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:13px;text-align:right;">{{captured_by_name}} → case opened by {{opened_by_name}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:12px;color:#7F1D1D;">Detected at · Case opened</td><td style="padding:8px 12px;border-bottom:1px solid #FEE2E2;font-size:13px;text-align:right;">{{captured_at}} · {{opened_at}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#7F1D1D;">Alert status</td><td style="padding:8px 12px;font-size:13px;text-align:right;font-weight:700;">{{alert_status}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:18px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#7F1D1D;font-weight:800;">ACT RIGHT NOW · CRITICAL</div>
  <div style="margin-top:6px;padding:12px 14px;background:#FFFFFF;border:2px solid #B91C1C;border-radius:8px;">
    {{{immediate_actions_html}}}
    <p style="margin:10px 0 0;font-size:12px;color:#7F1D1D;font-style:italic;">⚠ These actions are time-critical. Any delay breaches the IHR 2005 notification window and the national 7-1-7 response target.</p>
  </div>
</td></tr>

<tr><td style="padding:18px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">WHO · traveller profile</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:8px;background:#F8FAFC;">
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Name · Age · Gender</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;"><strong>{{traveler_name}}</strong> · {{traveler_age}} · {{traveler_gender}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Nationality · Occupation</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;">{{traveler_nationality}} · {{traveler_occupation}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Residence</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;">{{traveler_residence}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Reach · Emergency contact</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;">{{traveler_phone}} / {{traveler_email}} · {{emergency_contact}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#475569;">Destination in country</td><td style="padding:8px 12px;font-size:13px;text-align:right;">{{destination_district}} — {{destination_address}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">WHEN · HOW · travel exposure</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:8px;background:#F8FAFC;">
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Direction · Purpose · Stay</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;">{{travel_direction}} · {{purpose_of_travel}} · {{length_of_stay}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Journey start · Embarkation</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;">{{journey_start}} · {{embarkation_port}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Conveyance · Seat</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;">{{conveyance_type}} {{conveyance_id}} · seat {{seat_number}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#475569;">Arrival · Departure</td><td style="padding:8px 12px;font-size:13px;text-align:right;">{{arrival_datetime}} → {{departure_datetime}}</td></tr>
  </table>
  <div style="margin-top:10px;padding:10px 12px;background:#F8FAFC;border-left:3px solid #B91C1C;">
    <div style="font-size:11px;text-transform:uppercase;color:#475569;font-weight:700;">Countries traversed</div>
    <div style="margin-top:4px;">{{{travel_html}}}</div>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">CLINICAL PICTURE</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:8px;background:#F8FAFC;">
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Triage · General appearance</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;font-weight:700;">{{triage_category}} · {{general_appearance}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:12px;color:#475569;">Emergency signs</td><td style="padding:8px 12px;border-bottom:1px solid #E2E8F0;font-size:13px;text-align:right;font-weight:700;color:#B91C1C;">{{emergency_signs}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#475569;">Syndromic classification</td><td style="padding:8px 12px;font-size:13px;text-align:right;">{{syndrome_classification}}</td></tr>
    {{{vitals_html}}}
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">SYMPTOMS · ({{symptoms_count}} recorded)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{symptoms_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">KEY EXPOSURES</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{exposures_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">WHY · Differential ({{suspected_count}})</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{suspected_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{disease_intel_html}}}</td></tr>

<tr><td style="padding:0 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">Recommended tests · specimens</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">
    {{{recommended_tests_html}}}
    <p style="margin:10px 0 0;font-size:12px;color:#475569;"><strong>Specimens to collect:</strong> {{disease_specimens}}</p>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">Bedside red flags</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{key_distinguishers_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">Samples collected ({{samples_count}})</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{samples_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">Officer disposition + notes</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">
    <p style="margin:0 0 6px;font-size:13px;"><strong>Disposition:</strong> {{final_disposition}} <span style="color:#64748B;">({{disposition_details}})</span></p>
    <p style="margin:0 0 6px;font-size:13px;"><strong>Outcome:</strong> {{screening_outcome}} · follow-up required: {{followup_required}} → {{followup_level}}</p>
    <p style="margin:0;font-size:13px;color:#0F172A;"><em>{{officer_notes}}</em></p>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">Required follow-ups ({{followups_count}} · {{followups_overdue_count}} overdue)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{followups_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#B91C1C;font-weight:800;">Context · prior alerts at {{poe_code}} (last 30 days)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">{{{prior_alerts_html}}}</div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#B91C1C;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Open {{alert_code}} in POE Sentinel console →</a>
  </div>
</td></tr>

HTML . $this->footer('CRITICAL ALERT') . self::WRAP_CLOSE;

        $text = <<<TEXT
POE SENTINEL — CRITICAL ALERT
{{alert_code}} · {{country_name}} · POE {{poe_code}} · District {{district_code}}
Title: {{alert_title}}
Summary: {{summary}}

ACT NOW — acknowledge within {{ack_hours}} hours (by {{ack_deadline}})
Escalation ladder: {{escalation_ladder}}

WHO: {{traveler_name}} · {{traveler_age}} · {{traveler_gender}} · {{traveler_nationality}} · occupation {{traveler_occupation}}
Residence: {{traveler_residence}} · reach {{traveler_phone}} / {{traveler_email}}
Destination in country: {{destination_district}} ({{destination_address}})

TRAVEL: {{travel_direction}} via {{conveyance_type}} {{conveyance_id}} seat {{seat_number}}
Journey start {{journey_start}} → embarkation {{embarkation_port}}
Arrival {{arrival_datetime}} · departure {{departure_datetime}}
Purpose {{purpose_of_travel}} · planned stay {{length_of_stay}}

CLINICAL: triage {{triage_category}} · general appearance {{general_appearance}} · emergency signs {{emergency_signs}}
Syndrome: {{syndrome_classification}}
Disposition: {{final_disposition}} ({{disposition_details}})
Officer notes: {{officer_notes}}

DISEASE INTEL: {{disease_name}} — {{disease_who_category}}
 · CFR {{disease_cfr_pct}}   · Incubation {{disease_incubation}}
 · Transmission: {{disease_transmission}}
 · PPE: {{disease_ppe}}
 · Isolation: {{disease_isolation}}
 · IHR notification: {{disease_ihr_notification}}
 · Case definition: {{disease_case_definition}}
 · Differential: {{disease_differential}}
 · Specimens: {{disease_specimens}}

OPEN IN CONSOLE → {{console_url}}
Alert created {{alert_created_at}} ({{alert_created_ago}}). Status {{alert_status}}.
{{country_name}} POE Sentinel · WHO IHR 2005 + AFRO IDSR 2021.
TEXT;

        return [
            'template_code' => 'ALERT_CRITICAL',
            'levels' => ['DISTRICT', 'PHEOC', 'NATIONAL', 'WHO'],
            'subject' => '⛔ CRITICAL · {{alert_code}} · {{disease_name}} · POE {{poe_code}} · act within {{ack_hours}}h',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  ALERT_HIGH
    // ═════════════════════════════════════════════════════════════════════
    private function alertHigh(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#92400E 0%,#D97706 60%,#F59E0B 100%);padding:24px 28px;">
  <div style="font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#FEF3C7;font-weight:700;">{{country_name}} · POE SENTINEL · IHR 2005</div>
  <div style="margin-top:6px;font-size:12px;color:#FEF3C7;font-weight:600;">HIGH-risk public health alert · acknowledge within {{ack_hours}} hours</div>
  <div style="margin-top:10px;font-size:24px;font-weight:800;color:#FFFFFF;line-height:1.15;">⚠ {{alert_title}}</div>
  <div style="margin-top:6px;font-size:14px;color:#FEF3C7;">{{summary}}</div>
</td></tr>

<tr><td style="padding:20px 28px 4px;">
  <p style="margin:0;font-size:13px;color:#0F172A;">A HIGH-risk public-health event has been flagged at {{poe_code}}. Review the case dossier, confirm disposition, and escalate to {{routed_to_level}} per the national ladder. Acknowledge in the console within {{ack_sla_hours}} hours to maintain the 7-1-7 response window.</p>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="background:#FEF3C7;border:1px solid #FCD34D;border-radius:8px;padding:12px 14px;">
    <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#92400E;font-weight:800;">Situation at a glance</div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;font-size:12px;">
      <tr><td style="padding:3px 0;color:#78350F;">Alert</td><td style="padding:3px 0;text-align:right;font-weight:700;">{{alert_code}}</td></tr>
      <tr><td style="padding:3px 0;color:#78350F;">Risk</td><td style="padding:3px 0;text-align:right;font-weight:700;color:#B45309;">{{risk_level_label}}</td></tr>
      <tr><td style="padding:3px 0;color:#78350F;">Location</td><td style="padding:3px 0;text-align:right;">POE {{poe_code}} · {{district_code}} · {{country_name}}</td></tr>
      <tr><td style="padding:3px 0;color:#78350F;">Detected by</td><td style="padding:3px 0;text-align:right;">{{captured_by_name}} at {{captured_at}}</td></tr>
      <tr><td style="padding:3px 0;color:#78350F;">Case opened by</td><td style="padding:3px 0;text-align:right;">{{opened_by_name}} at {{opened_at}}</td></tr>
      <tr><td style="padding:3px 0;color:#78350F;">Acknowledge by</td><td style="padding:3px 0;text-align:right;font-weight:700;">{{ack_deadline}}</td></tr>
      <tr><td style="padding:3px 0;color:#78350F;">Ladder</td><td style="padding:3px 0;text-align:right;">{{escalation_ladder}}</td></tr>
    </table>
  </div>
</td></tr>

<tr><td style="padding:18px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Traveller profile</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;font-size:12px;">
    <tr><td style="padding:4px 0;color:#475569;">Identity</td><td style="padding:4px 0;text-align:right;font-weight:700;">{{traveler_name}} · {{traveler_age}} · {{traveler_gender}}</td></tr>
    <tr><td style="padding:4px 0;color:#475569;">Nationality · Residence</td><td style="padding:4px 0;text-align:right;">{{traveler_nationality}} · {{traveler_residence}}</td></tr>
    <tr><td style="padding:4px 0;color:#475569;">Occupation</td><td style="padding:4px 0;text-align:right;">{{traveler_occupation}}</td></tr>
    <tr><td style="padding:4px 0;color:#475569;">Destination</td><td style="padding:4px 0;text-align:right;">{{destination_district}} · {{destination_address}}</td></tr>
    <tr><td style="padding:4px 0;color:#475569;">Reach</td><td style="padding:4px 0;text-align:right;">{{traveler_phone}} · {{traveler_email}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Travel history</div>
  <div style="margin-top:8px;padding:10px 14px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">
    <p style="margin:0 0 4px;font-size:12px;color:#78350F;">{{travel_direction}} · {{conveyance_type}} {{conveyance_id}} · seat {{seat_number}} · arrival {{arrival_datetime}}</p>
    {{{travel_html}}}
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Clinical picture</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#78350F;">Triage · general appearance</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{triage_category}} · {{general_appearance}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#78350F;">Emergency signs</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;color:#B45309;">{{emergency_signs}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#78350F;">Syndrome</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{syndrome_classification}}</td></tr>
    {{{vitals_html}}}
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Symptoms ({{symptoms_count}}) &amp; exposures</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">
    {{{symptoms_html}}}
    <hr style="border:none;border-top:1px dashed #FCD34D;margin:10px 0;">
    {{{exposures_html}}}
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Differential ({{suspected_count}})</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">{{{suspected_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{disease_intel_html}}}</td></tr>

<tr><td style="padding:0 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Immediate actions</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFFFFF;border:2px solid #F59E0B;border-radius:8px;">
    {{{immediate_actions_html}}}
    <p style="margin:10px 0 0;font-size:12px;color:#92400E;">Recommended tests: see below. Collect specimens per disease protocol: <strong>{{disease_specimens}}</strong>.</p>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Recommended tests</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">{{{recommended_tests_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Samples &amp; follow-ups</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">
    <p style="margin:0 0 6px;font-size:12px;color:#78350F;"><strong>Samples recorded ({{samples_count}})</strong></p>
    {{{samples_html}}}
    <hr style="border:none;border-top:1px dashed #FCD34D;margin:10px 0;">
    <p style="margin:0 0 6px;font-size:12px;color:#78350F;"><strong>Follow-up actions ({{followups_count}} seeded · {{followups_overdue_count}} overdue)</strong></p>
    {{{followups_html}}}
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#92400E;font-weight:800;">Context · prior alerts at {{poe_code}}</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFFBEB;border:1px solid #FCD34D;border-radius:8px;">{{{prior_alerts_html}}}</div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#D97706;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Open {{alert_code}} in POE Sentinel →</a>
  </div>
</td></tr>

HTML . $this->footer('HIGH-RISK ALERT') . self::WRAP_CLOSE;

        $text = <<<TEXT
POE SENTINEL — HIGH-RISK ALERT
{{alert_code}} · {{country_name}} · POE {{poe_code}}
{{alert_title}}

{{summary}}

Acknowledge by {{ack_deadline}} ({{ack_hours}}h). Ladder: {{escalation_ladder}}.

TRAVELLER: {{traveler_name}} · {{traveler_age}} · {{traveler_gender}} · {{traveler_nationality}}
Travel: {{travel_direction}} {{conveyance_type}} {{conveyance_id}} seat {{seat_number}} · arrival {{arrival_datetime}}
Purpose {{purpose_of_travel}} · stay {{length_of_stay}}
Destination: {{destination_district}} — {{destination_address}}

CLINICAL: {{triage_category}} · {{general_appearance}} · emergency signs {{emergency_signs}}
Syndrome: {{syndrome_classification}}
Disposition: {{final_disposition}} ({{disposition_details}})

DISEASE: {{disease_name}} ({{disease_who_category}})
CFR {{disease_cfr_pct}} · Incubation {{disease_incubation}}
Transmission: {{disease_transmission}}
PPE: {{disease_ppe}}
Isolation: {{disease_isolation}}
IHR: {{disease_ihr_notification}}
Case def: {{disease_case_definition}}
Differential: {{disease_differential}}
Specimens: {{disease_specimens}}

Follow-ups: {{followups_count}} seeded, {{followups_overdue_count}} overdue.
Open in console → {{console_url}}
TEXT;

        return [
            'template_code' => 'ALERT_HIGH',
            'levels' => ['DISTRICT', 'PHEOC', 'NATIONAL'],
            'subject' => '⚠ HIGH · {{alert_code}} · {{disease_name}} · POE {{poe_code}}',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  TIER1_ADVISORY
    // ═════════════════════════════════════════════════════════════════════
    private function tier1Advisory(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#0C1B3A 0%,#1E293B 55%,#0F172A 100%);padding:26px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#FCD34D;font-weight:700;">IHR 2005 · TIER 1 · ALWAYS NOTIFIABLE</div>
  <div style="margin-top:6px;font-size:12px;color:#E2E8F0;font-weight:600;">A single suspected case triggers WHO notification within 24 hours.</div>
  <div style="margin-top:12px;font-size:22px;font-weight:800;color:#FFFFFF;line-height:1.15;">⚕ {{disease_name}} — suspected case</div>
  <div style="margin-top:8px;font-size:14px;color:#E2E8F0;">{{alert_title}}</div>
  <div style="margin-top:14px;padding:10px 14px;background:rgba(252,211,77,0.12);border:1px solid rgba(252,211,77,0.3);border-radius:6px;">
    <div style="font-size:12px;color:#FDE68A;"><strong>{{country_name}}</strong> · POE {{poe_code}} · {{district_code}} · alert {{alert_code}}</div>
    <div style="font-size:12px;color:#FCD34D;margin-top:4px;">Status {{alert_status}} · raised {{alert_created_at}}</div>
  </div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;"><strong>Regulatory context.</strong> Under the International Health Regulations (2005), <em>{{disease_name}}</em> is in the WHO <strong>Tier 1 always-notifiable</strong> list. A single laboratory-confirmed OR clinically-suspected case constitutes a potential Public Health Emergency of International Concern and must be notified to WHO through the National IHR Focal Point within <strong>24 hours of detection</strong>.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Disease profile — {{disease_name}}</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F1F5F9;border-left:4px solid #FCD34D;border-radius:6px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="font-size:12px;">
      <tr><td style="padding:3px 0;color:#475569;">WHO category</td><td style="padding:3px 0;text-align:right;font-weight:700;">{{disease_who_category}}</td></tr>
      <tr><td style="padding:3px 0;color:#475569;">Case fatality rate</td><td style="padding:3px 0;text-align:right;font-weight:700;">{{disease_cfr_pct}}</td></tr>
      <tr><td style="padding:3px 0;color:#475569;">Incubation</td><td style="padding:3px 0;text-align:right;">{{disease_incubation}}</td></tr>
      <tr><td style="padding:3px 0;color:#475569;vertical-align:top;">Transmission</td><td style="padding:3px 0;text-align:right;">{{disease_transmission}}</td></tr>
      <tr><td style="padding:3px 0;color:#475569;vertical-align:top;">PPE required</td><td style="padding:3px 0;text-align:right;">{{disease_ppe}}</td></tr>
      <tr><td style="padding:3px 0;color:#475569;vertical-align:top;">Isolation</td><td style="padding:3px 0;text-align:right;">{{disease_isolation}}</td></tr>
      <tr><td style="padding:3px 0;color:#475569;vertical-align:top;">IHR notification window</td><td style="padding:3px 0;text-align:right;color:#B91C1C;font-weight:700;">{{disease_ihr_notification}}</td></tr>
    </table>
    <p style="margin:10px 0 0;font-size:12px;color:#0F172A;"><strong>WHO case definition:</strong> {{disease_case_definition}}</p>
  </div>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Tier 1 response protocol</div>
  <ol style="margin:10px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:6px 0;"><strong>Immediate isolation</strong> of the suspected case per the disease-specific posture ({{disease_isolation}}).</li>
    <li style="margin:6px 0;"><strong>Full PPE</strong> for all subsequent contact ({{disease_ppe}}).</li>
    <li style="margin:6px 0;"><strong>Stop onward transport</strong> — conveyance {{conveyance_type}} {{conveyance_id}}, seat {{seat_number}}. Quarantine contacts.</li>
    <li style="margin:6px 0;"><strong>National IHR NFP notification</strong> within 24h. Risk assessment under Annex 2.</li>
    <li style="margin:6px 0;"><strong>Laboratory confirmation</strong> — specimens: {{disease_specimens}}.</li>
    <li style="margin:6px 0;"><strong>Contact tracing</strong> based on disease incubation ({{disease_incubation}}).</li>
    <li style="margin:6px 0;"><strong>Public risk communication</strong> coordinated with national MoH / WHO country office.</li>
  </ol>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Case dossier</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:6px;background:#F8FAFC;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Traveller</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{traveler_name}} · {{traveler_age}} · {{traveler_gender}} · {{traveler_nationality}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Occupation · residence</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_occupation}} · {{traveler_residence}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Travel</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{travel_direction}} · {{journey_start}} → {{embarkation_port}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Conveyance</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{conveyance_type}} {{conveyance_id}} · seat {{seat_number}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Timing</td><td style="padding:6px 12px;font-size:12px;text-align:right;">arrival {{arrival_datetime}} · detected {{captured_at}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Clinical</td><td style="padding:6px 12px;font-size:12px;text-align:right;">triage {{triage_category}} · emergency signs {{emergency_signs}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{vitals_html_wrap}}}
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Vitals</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:6px;background:#F8FAFC;">{{{vitals_html}}}</table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Symptoms ({{symptoms_count}}) + exposures</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;">
    {{{symptoms_html}}}<hr style="border:none;border-top:1px dashed #E2E8F0;margin:10px 0;">{{{exposures_html}}}
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Red-flag findings — bedside</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;">{{{key_distinguishers_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Differential diagnosis ({{suspected_count}} ranked)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;">
    {{{suspected_html}}}
    <p style="margin:10px 0 0;font-size:12px;color:#475569;"><strong>Standard differential to exclude:</strong> {{disease_differential}}.</p>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Immediate actions</div>
  <div style="margin-top:8px;padding:12px 14px;background:#0F172A;border-radius:6px;">
    <div style="color:#FCD34D;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;font-weight:700;">Execute now · non-negotiable</div>
    <div style="margin-top:8px;">{{{immediate_actions_html}}}</div>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0C1B3A;font-weight:800;">Follow-ups ({{followups_count}} · {{followups_overdue_count}} overdue)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;">{{{followups_html}}}</div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:linear-gradient(135deg,#1E293B 0%,#0F172A 100%);border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FCD34D;font-size:14px;font-weight:700;text-decoration:none;">Acknowledge {{alert_code}} in POE Sentinel →</a>
  </div>
</td></tr>

HTML . $this->footer('IHR TIER 1 ADVISORY') . self::WRAP_CLOSE;

        $text = <<<TEXT
POE SENTINEL — IHR TIER 1 ADVISORY
{{disease_name}} — suspected case
{{country_name}} · POE {{poe_code}} · alert {{alert_code}}

REGULATORY: under IHR 2005, {{disease_name}} is in the WHO Tier 1 always-notifiable list.
Single suspected case → notify WHO via national IHR NFP within 24h.

DISEASE PROFILE:
 · WHO category: {{disease_who_category}}
 · CFR: {{disease_cfr_pct}}
 · Incubation: {{disease_incubation}}
 · Transmission: {{disease_transmission}}
 · PPE: {{disease_ppe}}
 · Isolation: {{disease_isolation}}
 · IHR window: {{disease_ihr_notification}}
 · Case definition: {{disease_case_definition}}
 · Differential: {{disease_differential}}
 · Specimens: {{disease_specimens}}

CASE: {{traveler_name}} · {{traveler_age}} · {{traveler_gender}} · {{traveler_nationality}}
Travel: {{travel_direction}} · {{journey_start}} → {{embarkation_port}} · {{conveyance_type}} {{conveyance_id}} seat {{seat_number}}
Arrival {{arrival_datetime}} · detected {{captured_at}}
Clinical: triage {{triage_category}} · emergency signs {{emergency_signs}} · syndrome {{syndrome_classification}}

Follow-ups seeded: {{followups_count}} ({{followups_overdue_count}} overdue).
Open in console → {{console_url}}
TEXT;

        return [
            'template_code' => 'TIER1_ADVISORY',
            'levels' => ['NATIONAL', 'WHO'],
            'subject' => '⚕ IHR Tier 1 · {{disease_name}} suspected · {{country_name}} POE {{poe_code}} · 24h WHO window',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  ANNEX2_HIT
    // ═════════════════════════════════════════════════════════════════════
    private function annex2Hit(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#4C1D95 0%,#5B21B6 55%,#7C3AED 100%);padding:26px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#E9D5FF;font-weight:700;">IHR 2005 · ANNEX 2 DECISION INSTRUMENT</div>
  <div style="margin-top:6px;font-size:12px;color:#EDE9FE;font-weight:600;">Event may constitute a public-health emergency of international concern.</div>
  <div style="margin-top:12px;font-size:22px;font-weight:800;color:#FFFFFF;line-height:1.15;">◆ Annex 2 criteria met — assess &amp; notify</div>
  <div style="margin-top:8px;font-size:14px;color:#EDE9FE;">{{alert_title}}</div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;">This event was flagged against the WHO IHR Annex 2 Decision Instrument. At least one Annex 2 pillar has fired and a national risk assessment is required. If 2 or more criteria are confirmed, the event must be notified to WHO through the National IHR Focal Point.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5B21B6;font-weight:800;">The four Annex 2 criteria</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;background:#F5F3FF;border:1px solid #DDD6FE;border-radius:8px;">
    <tr>
      <td style="padding:10px 14px;border-bottom:1px solid #DDD6FE;">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#6D28D9;font-weight:700;">1 · Serious public-health impact</div>
        <div style="font-size:12px;color:#0F172A;margin-top:2px;">High case-fatality, rapid progression, vulnerable populations, healthcare system strain.</div>
      </td>
    </tr>
    <tr>
      <td style="padding:10px 14px;border-bottom:1px solid #DDD6FE;">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#6D28D9;font-weight:700;">2 · Unusual / unexpected</div>
        <div style="font-size:12px;color:#0F172A;margin-top:2px;">Unknown aetiology, unusual clinical course, unexpected geographical spread, emergence of resistance.</div>
      </td>
    </tr>
    <tr>
      <td style="padding:10px 14px;border-bottom:1px solid #DDD6FE;">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#6D28D9;font-weight:700;">3 · Significant risk of international spread</div>
        <div style="font-size:12px;color:#0F172A;margin-top:2px;">Evidence of cross-border transmission, infected travellers, contaminated conveyances, contacts crossing borders.</div>
      </td>
    </tr>
    <tr>
      <td style="padding:10px 14px;">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#6D28D9;font-weight:700;">4 · Significant risk of international travel / trade restrictions</div>
        <div style="font-size:12px;color:#0F172A;margin-top:2px;">Event likely to prompt other states to restrict movement / trade / conveyances.</div>
      </td>
    </tr>
  </table>
  <p style="margin:8px 0 0;font-size:11px;color:#5B21B6;"><strong>Rule of thumb:</strong> if any 2 of the 4 criteria apply → WHO notification is mandatory within 24 hours.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5B21B6;font-weight:800;">Event context</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:6px;background:#F8FAFC;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Alert · country · POE</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{alert_code}} · {{country_name}} · {{poe_code}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Suspected disease</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{disease_name}} · {{disease_who_category}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">CFR</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{disease_cfr_pct}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Traveller</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_name}} · {{traveler_age}} · {{traveler_nationality}} → {{country_name}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Travel path</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{journey_start}} → {{embarkation_port}} → {{poe_code}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Conveyance · seat</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{conveyance_type}} {{conveyance_id}} · seat {{seat_number}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Detected</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{captured_at}} · {{captured_by_name}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5B21B6;font-weight:800;">Cross-border spread signal</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F5F3FF;border:1px solid #DDD6FE;border-radius:8px;">
    <div style="font-size:12px;color:#0F172A;">Travel history on file:</div>
    <div style="margin-top:6px;">{{{travel_html}}}</div>
    <p style="margin:10px 0 0;font-size:12px;color:#5B21B6;"><em>Every country listed must be considered for cross-border notification to their IHR NFP if the case is confirmed.</em></p>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5B21B6;font-weight:800;">Clinical evidence</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;">
    <p style="margin:0 0 6px;font-size:12px;"><strong>Syndrome:</strong> {{syndrome_classification}} · <strong>triage:</strong> {{triage_category}} · <strong>ER signs:</strong> {{emergency_signs}}</p>
    {{{symptoms_html}}}
    <hr style="border:none;border-top:1px dashed #E2E8F0;margin:10px 0;">
    {{{exposures_html}}}
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{disease_intel_html}}}</td></tr>

<tr><td style="padding:0 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5B21B6;font-weight:800;">Expected actions — NATIONAL IHR NFP</div>
  <ol style="margin:10px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:6px 0;">Complete Annex 2 decision instrument within <strong>48 hours</strong>.</li>
    <li style="margin:6px 0;">Coordinate multi-sectoral risk assessment (MoH + IHR NFP + PHEOC).</li>
    <li style="margin:6px 0;">If 2+ criteria confirmed → submit IHR notification to WHO within <strong>24 hours</strong>.</li>
    <li style="margin:6px 0;">Pre-warn neighbouring country IHR NFPs if cross-border spread plausible.</li>
    <li style="margin:6px 0;">Initiate appropriate border-health measures (screening, tracing, quarantine).</li>
    <li style="margin:6px 0;">Prepare public risk communication with WHO country office.</li>
  </ol>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5B21B6;font-weight:800;">Current follow-up obligations ({{followups_count}})</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;">{{{followups_html}}}</div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#5B21B6;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Complete Annex 2 assessment →</a>
  </div>
</td></tr>

HTML . $this->footer('IHR ANNEX 2 ASSESSMENT') . self::WRAP_CLOSE;

        $text = <<<TEXT
POE SENTINEL — IHR ANNEX 2 DECISION INSTRUMENT
Alert {{alert_code}} · {{country_name}} · POE {{poe_code}}

At least one of the four Annex 2 criteria has fired. National risk assessment required.
If 2+ criteria → WHO notification mandatory within 24h.

CRITERIA (rule: 2 of 4 → notify):
 1. Serious public-health impact
 2. Unusual or unexpected event
 3. Significant risk of international spread
 4. Significant risk of travel/trade restrictions

EVENT:
 · Disease: {{disease_name}} ({{disease_who_category}})
 · CFR: {{disease_cfr_pct}}
 · Traveller: {{traveler_name}} · {{traveler_age}} · {{traveler_nationality}}
 · Path: {{journey_start}} → {{embarkation_port}} → {{poe_code}}
 · Conveyance: {{conveyance_type}} {{conveyance_id}} seat {{seat_number}}
 · Detected: {{captured_at}} by {{captured_by_name}}
 · Syndrome: {{syndrome_classification}} · triage {{triage_category}} · ER signs {{emergency_signs}}

IHR notification window: {{disease_ihr_notification}}
Transmission: {{disease_transmission}}
Differential: {{disease_differential}}

Open Annex 2 workflow → {{console_url}}
TEXT;

        return [
            'template_code' => 'ANNEX2_HIT',
            'levels' => ['PHEOC', 'NATIONAL', 'WHO'],
            'subject' => '◆ IHR Annex 2 criteria met · {{disease_name}} · {{country_name}} POE {{poe_code}}',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  ALERT_CASE_FILE
    // ═════════════════════════════════════════════════════════════════════
    private function alertCaseFile(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#134E4A 0%,#0F766E 55%,#14B8A6 100%);padding:24px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#CCFBF1;font-weight:700;">CASE FILE · dispatch to response partners</div>
  <div style="margin-top:6px;font-size:12px;color:#99F6E4;font-weight:600;">Traveller dispositioned — case file forwarded for continuity of care / contact tracing.</div>
  <div style="margin-top:10px;font-size:22px;font-weight:800;color:#FFFFFF;line-height:1.2;">🗂 {{alert_code}} · {{disease_name}}</div>
  <div style="margin-top:6px;font-size:13px;color:#CCFBF1;">{{summary}}</div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;">This is the <strong>complete case dispatch package</strong> for receiving teams (DISTRICT + PHEOC + receiving hospital + contact tracers). It contains every field captured at {{poe_code}} so you can receive, isolate, treat, investigate and trace without re-interviewing the traveller.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">1 · IDENTIFICATION</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #CCFBF1;border-radius:6px;background:#F0FDFA;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Name · Age · Gender · DOB</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{traveler_name}} · {{traveler_age}} · {{traveler_gender}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Nationality</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_nationality}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Occupation</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_occupation}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Residence country</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_residence}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Contact · phone / email</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_phone}} · {{traveler_email}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Emergency contact</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{emergency_contact}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Destination in {{country_name}}</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{destination_district}} · {{destination_address}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">2 · TRAVEL HISTORY</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #CCFBF1;border-radius:6px;background:#F0FDFA;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Direction · purpose · stay</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{travel_direction}} · {{purpose_of_travel}} · {{length_of_stay}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Journey start</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{journey_start}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Embarkation port / city</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{embarkation_port}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Conveyance · seat</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{conveyance_type}} {{conveyance_id}} · seat {{seat_number}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Arrival → departure</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{arrival_datetime}} → {{departure_datetime}}</td></tr>
  </table>
  <div style="margin-top:8px;padding:10px 12px;background:#F0FDFA;border-left:3px solid #14B8A6;border-radius:4px;">
    <div style="font-size:11px;text-transform:uppercase;color:#115E59;font-weight:700;">Countries visited / transited</div>
    <div style="margin-top:4px;">{{{travel_html}}}</div>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">3 · CLINICAL FINDINGS</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #CCFBF1;border-radius:6px;background:#F0FDFA;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Triage · general appearance</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{triage_category}} · {{general_appearance}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Emergency signs present</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{emergency_signs}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Syndromic classification</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{syndrome_classification}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#115E59;">Assigned risk</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{case_risk_level}}</td></tr>
    {{{vitals_html}}}
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">4 · SYMPTOMS · {{symptoms_count}}</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">{{{symptoms_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">5 · EXPOSURES</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">{{{exposures_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">6 · DIFFERENTIAL · {{suspected_count}} ranked</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">{{{suspected_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{disease_intel_html}}}</td></tr>

<tr><td style="padding:0 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">7 · SAMPLES COLLECTED · {{samples_count}}</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">{{{samples_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">8 · DISPOSITION &amp; OFFICER NOTES</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">
    <p style="margin:0 0 6px;font-size:13px;"><strong>Final disposition:</strong> {{final_disposition}}</p>
    <p style="margin:0 0 6px;font-size:13px;"><strong>Detail:</strong> {{disposition_details}}</p>
    <p style="margin:0 0 6px;font-size:13px;"><strong>Outcome:</strong> {{screening_outcome}} · <strong>follow-up:</strong> {{followup_required}} @ {{followup_level}}</p>
    <p style="margin:10px 0 0;font-size:13px;color:#0F172A;"><strong>Officer notes:</strong><br><em>{{officer_notes}}</em></p>
  </div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">9 · ACTIONS TAKEN AT POE</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">{{{sec_actions_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">10 · FOLLOW-UPS EXPECTED ({{followups_count}} · {{followups_overdue_count}} overdue)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F0FDFA;border:1px solid #CCFBF1;border-radius:6px;">{{{followups_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#0F766E;font-weight:800;">11 · CONTINUITY OF CARE · what receiving teams must do</div>
  <ul style="margin:8px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:5px 0;">Re-verify identity on arrival using the initials/anonymous code above.</li>
    <li style="margin:5px 0;">Maintain isolation posture per disease: <strong>{{disease_isolation}}</strong>. PPE: {{disease_ppe}}.</li>
    <li style="margin:5px 0;">Collect any missing specimens: {{disease_specimens}}.</li>
    <li style="margin:5px 0;">Initiate/continue the {{followups_count}} seeded RTSL-14 follow-ups; blocks_closure flags matter.</li>
    <li style="margin:5px 0;">Trace contacts per disease incubation window: {{disease_incubation}}.</li>
    <li style="margin:5px 0;">Notify {{routed_to_level}} + national IHR NFP per: {{disease_ihr_notification}}.</li>
  </ul>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#0F766E;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Open full case file in console →</a>
  </div>
</td></tr>

HTML . $this->footer('CASE-FILE DISPATCH') . self::WRAP_CLOSE;

        $text = <<<TEXT
CASE FILE — DISPATCH PACKAGE
{{alert_code}} · {{country_name}} · POE {{poe_code}} → routed_to {{routed_to_level}}
Disease: {{disease_name}} ({{disease_who_category}}) · CFR {{disease_cfr_pct}}

IDENTIFICATION
 · Traveller: {{traveler_name}} · {{traveler_age}} · {{traveler_gender}} · {{traveler_nationality}}
 · Occupation: {{traveler_occupation}}
 · Residence: {{traveler_residence}}
 · Contact: {{traveler_phone}} / {{traveler_email}}
 · Emergency contact: {{emergency_contact}}
 · Destination: {{destination_district}} ({{destination_address}})

TRAVEL
 · Direction {{travel_direction}} · purpose {{purpose_of_travel}} · stay {{length_of_stay}}
 · Journey start: {{journey_start}} · embarkation: {{embarkation_port}}
 · Conveyance: {{conveyance_type}} {{conveyance_id}} seat {{seat_number}}
 · Arrival → departure: {{arrival_datetime}} → {{departure_datetime}}

CLINICAL
 · Triage: {{triage_category}} · appearance: {{general_appearance}} · emergency signs: {{emergency_signs}}
 · Syndrome: {{syndrome_classification}} · assigned risk {{case_risk_level}}

DISPOSITION
 · {{final_disposition}} — {{disposition_details}}
 · Outcome: {{screening_outcome}} · follow-up {{followup_required}} @ {{followup_level}}
 · Officer notes: {{officer_notes}}

DISEASE INTEL
 · Incubation: {{disease_incubation}} · transmission: {{disease_transmission}}
 · PPE: {{disease_ppe}} · isolation: {{disease_isolation}}
 · IHR: {{disease_ihr_notification}}
 · Case def: {{disease_case_definition}}
 · Differential: {{disease_differential}}
 · Specimens to collect: {{disease_specimens}}

Follow-ups: {{followups_count}} seeded · {{followups_overdue_count}} overdue
Samples: {{samples_count}}
Open in console → {{console_url}}
TEXT;

        return [
            'template_code' => 'ALERT_CASE_FILE',
            'levels' => ['DISTRICT', 'PHEOC', 'NATIONAL'],
            'subject' => '🗂 CASE FILE · {{alert_code}} · {{traveler_name}} · {{disease_name}} · disposition {{final_disposition}}',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  BREACH_717
    // ═════════════════════════════════════════════════════════════════════
    private function breach717(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#000000 0%,#7F1D1D 60%,#991B1B 100%);padding:26px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#FECACA;font-weight:700;">7 · 1 · 7 FRAMEWORK BREACH</div>
  <div style="margin-top:6px;font-size:12px;color:#FCA5A5;font-weight:600;">Response stage missed — root-cause review required immediately.</div>
  <div style="margin-top:12px;font-size:24px;font-weight:800;color:#FFFFFF;line-height:1.15;">⏱ {{alert_code}} breached the 7-1-7 clock</div>
  <div style="margin-top:8px;font-size:13px;color:#FECACA;">{{alert_title}}</div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;">The global 7-1-7 target for outbreak response (<strong>7 days</strong> to detect, <strong>1 day</strong> to notify, <strong>7 days</strong> for effective early response) has been missed on this alert. This email is the breach notification for the record. A <strong>bottleneck review + root-cause analysis</strong> must be completed and attached to the alert in the console within 24 hours.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#7F1D1D;font-weight:800;">Timeline · where did time go?</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;background:#FEE2E2;border:1px solid #FCA5A5;border-radius:8px;">
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FCA5A5;font-size:12px;color:#7F1D1D;font-weight:700;">DETECT · target ≤7 days from first signal</td><td style="padding:8px 12px;border-bottom:1px solid #FCA5A5;font-size:12px;text-align:right;">first signal {{captured_at}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FCA5A5;font-size:12px;color:#7F1D1D;font-weight:700;">NOTIFY · target ≤1 day from detection</td><td style="padding:8px 12px;border-bottom:1px solid #FCA5A5;font-size:12px;text-align:right;">alert raised {{alert_created_at}}</td></tr>
    <tr><td style="padding:8px 12px;border-bottom:1px solid #FCA5A5;font-size:12px;color:#7F1D1D;font-weight:700;">RESPOND · target effective response ≤7 days</td><td style="padding:8px 12px;border-bottom:1px solid #FCA5A5;font-size:12px;text-align:right;">{{followups_overdue_count}} follow-ups overdue of {{followups_count}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#7F1D1D;font-weight:700;">Acknowledgement state</td><td style="padding:8px 12px;font-size:12px;text-align:right;">by {{acknowledged_by_name}} at {{alert_acknowledged_at}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#7F1D1D;font-weight:800;">Root-cause questions · answer in the console</div>
  <ol style="margin:8px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:6px 0;">Was the <strong>primary signal</strong> recognised on time? What delayed detection?</li>
    <li style="margin:6px 0;">What caused the <strong>notification gap</strong> between first symptom and alert creation?</li>
    <li style="margin:6px 0;">Which <strong>follow-up actions</strong> are lagging? Who owns them?</li>
    <li style="margin:6px 0;">Are there <strong>resource constraints</strong> (PPE, transport, lab turnaround, staff)?</li>
    <li style="margin:6px 0;">What is the <strong>mitigation plan</strong> so this POE does not breach the next alert?</li>
  </ol>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#7F1D1D;font-weight:800;">Case context</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:6px;background:#F8FAFC;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Disease · risk</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{disease_name}} · {{risk_level_label}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Country · POE · district</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{country_name}} · {{poe_code}} · {{district_code}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Traveller</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{traveler_name}} · {{traveler_age}} · {{traveler_nationality}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Routed to</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{routed_to_level}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Ladder</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{escalation_ladder}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#7F1D1D;font-weight:800;">Follow-ups that need owners NOW</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FEF2F2;border:1px solid #FCA5A5;border-radius:6px;">{{{followups_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#7F1D1D;font-weight:800;">Prior alerts at {{poe_code}}</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;">{{{prior_alerts_html}}}</div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#991B1B;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Log 7-1-7 root-cause for {{alert_code}} →</a>
  </div>
</td></tr>

HTML . $this->footer('7-1-7 BREACH NOTICE') . self::WRAP_CLOSE;

        $text = <<<TEXT
7-1-7 BREACH — {{alert_code}}
{{country_name}} · POE {{poe_code}} · disease {{disease_name}} · risk {{risk_level_label}}

The 7-1-7 target (detect ≤7d · notify ≤1d · respond ≤7d) has been missed.
A root-cause review must be filed in the console within 24h.

TIMELINE
 · Detect: first signal {{captured_at}}
 · Notify: alert raised {{alert_created_at}}
 · Respond: {{followups_overdue_count}} of {{followups_count}} follow-ups overdue
 · Acknowledged by: {{acknowledged_by_name}} at {{alert_acknowledged_at}}

ROOT-CAUSE QUESTIONS
 1. Why was the signal delayed?
 2. Why was alert creation delayed?
 3. Which follow-ups are stuck?
 4. Resource constraints?
 5. Mitigation plan?

Open in console → {{console_url}}
TEXT;

        return [
            'template_code' => 'BREACH_717',
            'levels' => ['PHEOC', 'NATIONAL'],
            'subject' => '⏱ 7-1-7 BREACH · {{alert_code}} · {{poe_code}} · root-cause due 24h',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  ESCALATION
    // ═════════════════════════════════════════════════════════════════════
    private function escalation(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#881337 0%,#BE123C 55%,#E11D48 100%);padding:26px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#FECDD3;font-weight:700;">ESCALATION · next level of command</div>
  <div style="margin-top:6px;font-size:12px;color:#FECDD3;font-weight:600;">This alert could not be resolved at the previous level and is being escalated.</div>
  <div style="margin-top:12px;font-size:22px;font-weight:800;color:#FFFFFF;line-height:1.15;">▲ {{alert_code}} escalated to {{routed_to_level}}</div>
  <div style="margin-top:8px;font-size:13px;color:#FECDD3;">{{alert_title}}</div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;">You are receiving this because {{alert_code}} requires decision-making capacity that does not sit at the POE or district level. Below is the rationale, the history so far, and the exact decisions expected of you.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#BE123C;font-weight:800;">Why this is being escalated</div>
  <ul style="margin:8px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:4px 0;">Risk classification: <strong>{{risk_level_label}}</strong>.</li>
    <li style="margin:4px 0;">Suspected disease: <strong>{{disease_name}}</strong> ({{disease_who_category}}) — CFR {{disease_cfr_pct}}.</li>
    <li style="margin:4px 0;">IHR notification window: {{disease_ihr_notification}}.</li>
    <li style="margin:4px 0;">{{followups_overdue_count}} of {{followups_count}} follow-up actions are already overdue.</li>
    <li style="margin:4px 0;">Escalation ladder in effect: {{escalation_ladder}}.</li>
  </ul>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#BE123C;font-weight:800;">Decisions expected of you</div>
  <ol style="margin:8px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:5px 0;">Acknowledge the alert in the console within <strong>{{ack_hours}} hours</strong> (by {{ack_deadline}}).</li>
    <li style="margin:5px 0;">Reassign owners for the {{followups_overdue_count}} overdue follow-ups.</li>
    <li style="margin:5px 0;">Authorise escalation to the next ladder level if appropriate.</li>
    <li style="margin:5px 0;">Confirm isolation posture per disease: {{disease_isolation}}.</li>
    <li style="margin:5px 0;">Coordinate with WHO country office if the Annex 2 criteria warrant notification.</li>
  </ol>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#BE123C;font-weight:800;">Snapshot of case</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:6px;background:#F8FAFC;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Traveller</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{traveler_name}} · {{traveler_age}} · {{traveler_nationality}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">POE · district</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{poe_code}} · {{district_code}} · {{country_name}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Syndrome · triage</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{syndrome_classification}} · {{triage_category}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Disposition</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{final_disposition}} ({{disposition_details}})</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Officer notes</td><td style="padding:6px 12px;font-size:12px;text-align:right;"><em>{{officer_notes}}</em></td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#BE123C;font-weight:800;">Outstanding follow-ups ({{followups_overdue_count}} overdue)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#FFF1F2;border:1px solid #FECDD3;border-radius:6px;">{{{followups_html}}}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{disease_intel_html}}}</td></tr>

<tr><td style="padding:0 28px 14px;">
  <div style="background:#BE123C;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Take command of {{alert_code}} →</a>
  </div>
</td></tr>

HTML . $this->footer('ESCALATION NOTICE') . self::WRAP_CLOSE;

        $text = <<<TEXT
ESCALATION — {{alert_code}}
{{country_name}} · POE {{poe_code}} · escalated to {{routed_to_level}}

Disease: {{disease_name}} ({{disease_who_category}}) · CFR {{disease_cfr_pct}}
Risk: {{risk_level_label}} · IHR window: {{disease_ihr_notification}}
{{followups_overdue_count}} of {{followups_count}} follow-ups overdue.

DECISIONS EXPECTED
 1. Acknowledge in console within {{ack_hours}}h (by {{ack_deadline}}).
 2. Reassign owners for overdue follow-ups.
 3. Authorise next-level escalation if appropriate.
 4. Confirm isolation posture: {{disease_isolation}}.
 5. Coordinate with WHO country office if Annex 2 threshold met.

CASE: {{traveler_name}} · {{traveler_age}} · {{traveler_nationality}}
Disposition: {{final_disposition}} ({{disposition_details}})
Notes: {{officer_notes}}

Escalation ladder: {{escalation_ladder}}
Open in console → {{console_url}}
TEXT;

        return [
            'template_code' => 'ESCALATION',
            'levels' => ['PHEOC', 'NATIONAL', 'WHO'],
            'subject' => '▲ ESCALATION · {{alert_code}} · to {{routed_to_level}} · {{disease_name}}',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  PHEIC_ADVISORY
    // ═════════════════════════════════════════════════════════════════════
    private function pheicAdvisory(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#1E1B4B 0%,#3730A3 55%,#6D28D9 100%);padding:26px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#DDD6FE;font-weight:700;">IHR 2005 · PHEIC PATHWAY</div>
  <div style="margin-top:6px;font-size:12px;color:#E0E7FF;font-weight:600;">Public Health Emergency of International Concern — WHO coordination pathway.</div>
  <div style="margin-top:12px;font-size:22px;font-weight:800;color:#FFFFFF;line-height:1.15;">▣ {{alert_code}} — candidate PHEIC event</div>
  <div style="margin-top:8px;font-size:13px;color:#DDD6FE;">{{alert_title}}</div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;">A suspected case consistent with a WHO Tier 1 always-notifiable disease has been recorded. Under IHR 2005 this may constitute a PHEIC. The national IHR NFP must complete the Annex 2 assessment and notify WHO within 24 hours of the event being known.</p>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#3730A3;font-weight:800;">Why PHEIC path applies</div>
  <ul style="margin:8px 0 0 20px;padding:0;font-size:13px;color:#0F172A;">
    <li style="margin:4px 0;">Disease <strong>{{disease_name}}</strong> is classified {{disease_who_category}}.</li>
    <li style="margin:4px 0;">Historical CFR: {{disease_cfr_pct}}; incubation window: {{disease_incubation}}.</li>
    <li style="margin:4px 0;">Transmission: {{disease_transmission}} — plausible international spread via {{conveyance_type}} {{conveyance_id}}.</li>
    <li style="margin:4px 0;">Travel path: {{journey_start}} → {{embarkation_port}} → {{poe_code}}, {{country_name}}.</li>
  </ul>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#3730A3;font-weight:800;">WHO PHEIC workflow expected</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;background:#EEF2FF;border:1px solid #C7D2FE;border-radius:8px;">
    <tr><td style="padding:8px 12px;font-size:12px;color:#3730A3;font-weight:700;width:28%;">0–24 h</td><td style="padding:8px 12px;font-size:12px;">Complete Annex 2 assessment. Notify WHO via national IHR NFP.</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#3730A3;font-weight:700;">24–48 h</td><td style="padding:8px 12px;font-size:12px;">WHO risk assessment + follow-up questions; consider IHR Emergency Committee.</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#3730A3;font-weight:700;">48 h+</td><td style="padding:8px 12px;font-size:12px;">If 2+ Annex 2 criteria confirmed → WHO DG may declare PHEIC, issue temporary recommendations.</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">{{{disease_intel_html}}}</td></tr>

<tr><td style="padding:0 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#3730A3;font-weight:800;">Case snapshot</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border:1px solid #E2E8F0;border-radius:6px;background:#F8FAFC;">
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Traveller</td><td style="padding:6px 12px;font-size:12px;text-align:right;font-weight:700;">{{traveler_name}} · {{traveler_age}} · {{traveler_gender}} · {{traveler_nationality}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Travel</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{travel_direction}} · {{journey_start}} → {{embarkation_port}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Conveyance · seat</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{conveyance_type}} {{conveyance_id}} · seat {{seat_number}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Arrival</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{arrival_datetime}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Syndrome</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{syndrome_classification}}</td></tr>
    <tr><td style="padding:6px 12px;font-size:12px;color:#475569;">Disposition</td><td style="padding:6px 12px;font-size:12px;text-align:right;">{{final_disposition}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#3730A3;font-weight:800;">Cross-border spread signal (travel history)</div>
  <div style="margin-top:8px;padding:12px 14px;background:#EEF2FF;border:1px solid #C7D2FE;border-radius:6px;">{{{travel_html}}}</div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#3730A3;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">Open PHEIC assessment workflow →</a>
  </div>
</td></tr>

HTML . $this->footer('PHEIC · IHR 2005') . self::WRAP_CLOSE;

        $text = <<<TEXT
PHEIC ADVISORY — {{alert_code}}
{{country_name}} · POE {{poe_code}} · suspected {{disease_name}}

Under IHR 2005 this may constitute a Public Health Emergency of International Concern.
National IHR NFP must complete the Annex 2 assessment and notify WHO within 24 hours.

DISEASE: {{disease_name}} ({{disease_who_category}})
CFR {{disease_cfr_pct}} · Incubation {{disease_incubation}}
Transmission: {{disease_transmission}}
Travel path: {{journey_start}} → {{embarkation_port}} → {{poe_code}}
Conveyance: {{conveyance_type}} {{conveyance_id}} seat {{seat_number}}

TIMELINE
 0–24 h  Annex 2 assessment → WHO IHR notification
 24–48 h WHO risk assessment / Emergency Committee consideration
 48 h+   Possible PHEIC declaration + temporary recommendations

Open PHEIC workflow → {{console_url}}
TEXT;

        return [
            'template_code' => 'PHEIC_ADVISORY',
            'levels' => ['NATIONAL', 'WHO'],
            'subject' => '▣ PHEIC pathway · {{disease_name}} · {{country_name}} · IHR NFP 24h window',
            'html' => $html,
            'text' => $text,
        ];
    }

    // ═════════════════════════════════════════════════════════════════════
    //  ALERT_CLOSED
    // ═════════════════════════════════════════════════════════════════════
    private function alertClosed(): array
    {
        $html = self::WRAP_OPEN . <<<'HTML'
<tr><td style="background:linear-gradient(135deg,#064E3B 0%,#047857 55%,#10B981 100%);padding:26px 28px;">
  <div style="font-size:11px;letter-spacing:0.22em;text-transform:uppercase;color:#A7F3D0;font-weight:700;">ALERT RESOLVED &amp; CLOSED</div>
  <div style="margin-top:6px;font-size:12px;color:#D1FAE5;font-weight:600;">The alert has been formally closed. This notice is the closure record.</div>
  <div style="margin-top:12px;font-size:22px;font-weight:800;color:#FFFFFF;line-height:1.15;">✓ {{alert_code}} closed</div>
  <div style="margin-top:8px;font-size:13px;color:#A7F3D0;">{{alert_title}}</div>
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <p style="margin:0;font-size:13px;color:#0F172A;">This alert has been closed at {{alert_closed_at}} by <strong>{{closed_by_name}}</strong>. Review the summary below and raise any concern before the record is archived at the next digest cycle.</p>
</td></tr>

<tr><td style="padding:16px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#047857;font-weight:800;">Closure record</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;background:#ECFDF5;border:1px solid #A7F3D0;border-radius:6px;">
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;">Alert</td><td style="padding:8px 12px;font-size:12px;text-align:right;font-weight:700;">{{alert_code}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;">Closed by</td><td style="padding:8px 12px;font-size:12px;text-align:right;font-weight:700;">{{closed_by_name}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;">Closed at</td><td style="padding:8px 12px;font-size:12px;text-align:right;">{{alert_closed_at}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;vertical-align:top;">Close reason</td><td style="padding:8px 12px;font-size:12px;text-align:right;">{{close_reason}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;">Risk at closure</td><td style="padding:8px 12px;font-size:12px;text-align:right;">{{risk_level_label}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;">Final disposition</td><td style="padding:8px 12px;font-size:12px;text-align:right;">{{final_disposition}} — {{disposition_details}}</td></tr>
    <tr><td style="padding:8px 12px;font-size:12px;color:#065F46;">Outcome</td><td style="padding:8px 12px;font-size:12px;text-align:right;">{{screening_outcome}}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#047857;font-weight:800;">Case summary</div>
  <p style="margin:6px 0 0;font-size:13px;color:#0F172A;">{{summary}}</p>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#047857;font-weight:800;">Follow-up status at closure ({{followups_count}})</div>
  <div style="margin-top:8px;padding:12px 14px;background:#ECFDF5;border:1px solid #A7F3D0;border-radius:6px;">{{{followups_html}}}</div>
  <p style="margin:6px 0 0;font-size:12px;color:#047857;">If {{followups_overdue_count}} &gt; 0 — this alert closed with outstanding follow-ups. A data-quality review may follow.</p>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#047857;font-weight:800;">Disease residual risk</div>
  <div style="margin-top:8px;padding:12px 14px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;font-size:12px;color:#0F172A;">
    <p style="margin:0 0 6px;"><strong>{{disease_name}}</strong> · incubation {{disease_incubation}} · transmission: {{disease_transmission}}.</p>
    <p style="margin:0;">Contacts should continue under monitoring through the incubation window even after alert closure. If anyone develops symptoms: re-open under a new alert.</p>
  </div>
</td></tr>

<tr><td style="padding:20px 28px 14px;">
  <div style="background:#047857;border-radius:8px;padding:14px 16px;text-align:center;">
    <a href="{{console_url}}" style="color:#FFFFFF;font-size:14px;font-weight:700;text-decoration:none;">View final record for {{alert_code}} →</a>
  </div>
</td></tr>

HTML . $this->footer('ALERT CLOSED') . self::WRAP_CLOSE;

        $text = <<<TEXT
ALERT CLOSED — {{alert_code}}
{{country_name}} · POE {{poe_code}}
Closed by {{closed_by_name}} at {{alert_closed_at}}

Reason: {{close_reason}}
Final disposition: {{final_disposition}} — {{disposition_details}}
Outcome: {{screening_outcome}}
Summary: {{summary}}

Follow-ups at closure: {{followups_count}} seeded · {{followups_overdue_count}} overdue
(If any remained overdue at closure → data-quality review may follow.)

RESIDUAL RISK — {{disease_name}}
 · Incubation: {{disease_incubation}}
 · Transmission: {{disease_transmission}}
Continue contact monitoring through incubation window. Re-open under a new alert if symptoms develop.

Open record → {{console_url}}
TEXT;

        return [
            'template_code' => 'ALERT_CLOSED',
            'levels' => ['DISTRICT', 'PHEOC', 'NATIONAL'],
            'subject' => '✓ CLOSED · {{alert_code}} · {{disease_name}} · {{final_disposition}} · by {{closed_by_name}}',
            'html' => $html,
            'text' => $text,
        ];
    }
}
